### ISSUE TITLE
Heal issue

### ISSUE THREAD

**Issue by Lukyrouge3** [w0dm4n/Noxus#1]
There is a problem with the heal effect : that only heal as we are level 1 ...
Sorry for my bad english

**Comment by w0dm4n** [comment]
L'émulateur n'est pas tenu à jour, et nous sommes pas en train de le développer, c'est certainement qu'il manque quelque chose, à toi de trouver l'erreur dans le code et de la fixer 😏

**Comment by Lukyrouge3** [comment]
Oké cimer quand même

**Comment by SwiTool** [comment]
Salut @w0dm4n, je suis à l'origine de Dofucks (dofucks.com) un bot pour Dofus Touch, et j'aurais aimé avoir un serveur privé (en nodejs) pour moi tout seul (histoire de pouvoir entrainer mes bots avec du machine learning).
Je suis tombé sur ton repo qui m'a l'air vraiment d'être une bonne base, cependant il n'y a aucune documentation d'utilisation. Est-ce qu'on pourrait se contacter en privé ?
Merci

**Comment by w0dm4n** [comment]
Salut, tu peux me contacter sur discord si tu le souhaite: Arkalius#1324
